vim.lsp.set_log_level("debug")

vim.lsp.enable('clangd')
vim.lsp.enable('rust-analyzer')
vim.lsp.enable('bash-language-server')
vim.lsp.enable('lua-language-server')
vim.lsp.enable('gopls')
vim.lsp.enable('fortls')
vim.lsp.enable('haskell-language-server')
vim.lsp.enable('zls')
